# Generated by Django 3.2.5 on 2021-07-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20210712_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='travel.user'),
            preserve_default=False,
        ),
    ]
